---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  # ----------------------- OPS -----------------------
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "150", --preserve-quotes]
        exclude: ^.github/dependabot.yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: shfmt
  # ------------------------- PYTHON ------------------------
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E402,E501"]
        exclude: ^migrations/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.6.0
    hooks:
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "poetry run mypy --no-strict-optional db_write_performance_benchmark"
        language: system
        types: [python]
